### ISSUE TITLE
Convert to tflite

### ISSUE THREAD

**Issue by ghost** [secretbatcave/Uk-Bird-Classifier#1]
How can i convert the largeBirds4.pb to tflite?
The following approach does not work:
tflite_convert \
  --output_file=/tmp/foo.tflite \
  --graph_def_file=/tmp/bla.pb \
  --input_arrays=input \
  --output_arrays=output

Actually i only need the classification of gray herons for my Pond.
Can you help me?

**Comment by secretbatcave** [comment]
Hello there

What errors do you get? I suspect it might be because this model is very old, and the version of tensorflow I used isn't supported anymore.

**Comment by ghost** [comment]
Thanks for the feedback. Meanwhile I found another model on Tensorflow Hub. Best Regards!
