### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by Jo59Devs** [secretbatcave/Uk-Bird-Classifier#2]
You wrote: "I have not included the dataset, as I don't own the copyright. However if you wish to obtain a copy, please get in touch".
Can I have the complete Dataset?

Thanks!

**Comment by secretbatcave** [comment]
Hello!  I have sent you an email, I'm sure we can sort something out. I need to find the data...

**Comment by fepegar** [comment]
Can I please have the dataset as well? :)
